services:
  nginx:
    image: nginx:latest
    container_name: quantix-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: on-failure

  frontend:
    image: us-east1-docker.pkg.dev/quantix-prod/quantix/frontend:latest
    container_name: quantix-frontend
    environment:
      - NEXT_PUBLIC_API_URL=/api
    restart: on-failure

  backend:
    image: us-east1-docker.pkg.dev/quantix-prod/quantix/backend:latest
    container_name: quantix-backend
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
    restart: on-failure