services:
  frontend:
    image: us-east1-docker.pkg.dev/quantix-505516/quantix/frontend:latest
    container_name: quantix-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: us-east1-docker.pkg.dev/quantix-505516/quantix/backend:latest
    container_name: quantix-backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15
    container_name: quantix-db
    environment:
      POSTGRES_USER: quantix
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quantix
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantix -d quantix"]
      interval: 3s
      timeout: 3s
      retries: 10