apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantix-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantix-db
  template:
    metadata:
      labels:
        app: quantix-db
    spec:
      containers:
        - name: db
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "quantix"
            - name: POSTGRES_PASSWORD
              value: "secret"
            - name: POSTGRES_DB
              value: "quantix"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: quantix-db
spec:
  selector:
    app: quantix-db
  ports:
    - port: 5432
      targetPort: 5432
