name: quantix-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  backend-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run backend tests
        env:
          PYTHONPATH: backend
          DB_URL: "postgresql://quantix:secret@host.docker.internal:5432/quantix"
          SECRET_KEY: "b0d7131c028d602e415a87456198c11c69d3ff2f0e1672141c0b926f18080657"
        run: pytest backend/tests/

  frontend-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix frontend

      - name: Run frontend tests
        run: npm test --prefix frontend