name: quantix-CD

on:
  workflow_run:
    workflows: ["quantix-CI"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: us-east1-docker.pkg.dev/quantix-505516/quantix/backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: us-east1-docker.pkg.dev/quantix-505516/quantix/frontend:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.SERVER_IP }}:8000

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Login to Artifact Registry
        run: |
          cat /gcp-key.json | docker login -u _json_key --password-stdin https://us-east1-docker.pkg.dev
      - name: Deploy on VM
        run: |
          cd /home/davidalaverdyan0/quantix
          docker compose pull
          docker compose up -d